name: Build
on:
  push:
    branches:
      - main
jobs:
  build_and_test_ubuntu:
    name: Linux Ubuntu 20.04 Bazel build <GCC 9.3.0>
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Mount Bazel Cache
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel
    - name: Build Repository
      run: |
        bazel build //...
